language: php
php:
  - 5.3
  - 5.4
services:
  - mongodb
before_script:
  - wget --quiet http://getcomposer.org/composer.phar
  - php composer.phar install
  - mkdir logs
  - touch logs/application.log
  - phpenv config-add travis-php.ini
script: phpunit -c module/SelfService/test/phpunit.xml