language: php
php:
  - 5.3
  - 5.4
services:
  - mongodb
before_script:
  - phpenv config-add travis-php.ini
  - wget --quiet http://getcomposer.org/composer.phar
  - php composer.phar install
  - mkdir logs
  - touch logs/application.log
script: phpunit -d memory_limit=768M -c module/SelfService/test/phpunit.xml